/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lang_myapplication_TestJni */

#ifndef _Included_com_lang_myapplication_TestJni
#define _Included_com_lang_myapplication_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lang_myapplication_TestJni
 * Method:    logV
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lang_myapplication_TestJni_logV
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
