/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lang_myapplication_Encrypt */

#ifndef _Included_com_lang_myapplication_Encrypt
#define _Included_com_lang_myapplication_Encrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lang_myapplication_Encrypt
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lang_myapplication_Encrypt_encrypt
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
